
name: .NET
on:
  push:
    branches: [ "develop","main" ]
  
env:
  SOURCE_DIR: ./HelperAPI/HelperAPI


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chechout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{SOURCE_DIR}}

    - name: Build 
      run: dotnet build --no-restore
      working-directory: ${{SOURCE_DIR}}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{SOURCE_DIR}}
