
name: .NET
on:
  push:
    branches: [ "develop","main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chechout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore ./HelperAPI/HelperAPI.sln

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
