
name: .NET
on:
  push:
    branches: [ "develop","main" ]
    
env:
  WORKING_DIR: ./HelperAPI/HelperAPI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Environment
      run: printenv
      
    - name: Develop
      if: ${{ env.GITHUB_REF == 'refs/heads/develop' }}
      run: echo "Running on develop"
    - name: Main      
      if: ${{ env.GITHUB_REF == 'refs/heads/main' }}
      run: echo "Running on main"
    
    - name: Chechout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIR }}


    - name: Build 
      run: dotnet build --no-restore
      working-directory: ${{ env.WORKING_DIR }}


    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.WORKING_DIR }}

