
name: .NET
on:
  push:
    branches: [ "develop","main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Image
      uses: docker/setup-buildx-action@v2.2.1
        
    

