
name: .NET
on:
  push:
    branches: [ "develop","main" ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Build Image
      uses: docker/build-push-action@v3.3.0
        
    

